# grafana Loki
version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki_config.yml
    volumes: 
      - loki_data:/loki
    networks:
      - observability
  
  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./config/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - observability

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - observability
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - loki
  
  prometheus: # for monitoring metrics
    image: prom/prometheus:3.4.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes: 
      - prometheus_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - observability

volumes:
  loki_data:
    driver: local
    # driver_opts:
    #   type: nfs
    #   o: addr=nfs.example.com, rw
  grafana_data:
    driver: local
  prometheus:
    driver: local
  

networks:
  observability:
    driver: bridge
    attachable: true