global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# scrapes Loki metrics (self-monitoring)
scrape_configs:
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
    scheme: http
    metrics_path: "/metrics"

  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]
    scheme: http

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]
    scheme: http