version: "3"

services:

  k6:
    image: grafana/k6:0.46.0
    container_name: k6
    command: run /scripts/test.js
    volumes:
      - ./scripts:/scripts
    networks:
      - load_testing
    depends_on:
      - influxdb
      - grafana

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - load_testing
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - load_testing
    command: influxd run --config /etc/influxdb/influxdb.conf
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

networks:
  loadtesting:
    driver: bridge

# volumes:
#   grafana_data:
#     driver: local
#   influxdb_data:
#     driver: local